//
// Keychain helper for iOS/Swift.
//
// https://github.com/evgenyneu/keychain-swift
//
// This file was automatically generated by combining multiple Swift source files.
//


// ----------------------------
//
// KeychainError.swift
//
// ----------------------------

//
//  KeychainError.swift
//  KeychainSwift
//
//  Created by Lennard Sprong on 20/02/2025.
//

import Foundation
import Security

public struct KeychainError : RawRepresentable, CustomStringConvertible {
    public init(rawValue: OSStatus) {
        self.rawValue = rawValue
    }
    
    public init(_ code: OSStatus) {
        rawValue = code
    }
    
    /// The result code for the operation.
    public let rawValue: OSStatus
    
    /// Retrieve the localized description for this error. This uses ``/Security/SecCopyErrorMessageString(_:_:)`` internally.
    public var localizedDescription: String {
        if let message = SecCopyErrorMessageString(rawValue, nil) {
            return message as String
        }
        return description
    }
    
    public var description: String {
        "KeychainError(\(rawValue))"
    }
}

extension KeychainError : Equatable {}

extension KeychainError : CustomNSError {
    public static var errorDomain: String { NSOSStatusErrorDomain }
}

extension KeychainError : LocalizedError {
    public var errorDescription: String? { localizedDescription }
}

// MARK: - Authentication Error Constants

extension KeychainError {
    /// The user canceled the authentication prompt (e.g., dismissed Face ID / Touch ID dialog).
    /// Check for this error to handle the case where the user explicitly declines to authenticate.
    public static var userCanceled: KeychainError { KeychainError(errSecUserCanceled) }

    /// Authentication failed (e.g., biometric verification failed after too many attempts,
    /// or the biometric enrollment has changed for an item protected with `.biometryCurrentSet`).
    public static var authFailed: KeychainError { KeychainError(errSecAuthFailed) }

    /// Interaction with the user is required to access the item, but is not allowed in the
    /// current context. This typically occurs when trying to read an access-controlled item
    /// while the app is in the background, or when the device is locked.
    public static var interactionNotAllowed: KeychainError { KeychainError(errSecInteractionNotAllowed) }
}


// ----------------------------
//
// KeychainSwift.swift
//
// ----------------------------

import Security
import Foundation

/**

A collection of helper functions for saving text and data in the keychain.

*/
open class KeychainSwift: @unchecked Sendable {
  
  var lastQueryParameters: [String: Any]? // Used by the unit tests

  var keyPrefix = "" // Can be useful in test.
  
  /**

  Specify an access group that will be used to access keychain items. Access groups can be used to share keychain items between applications. When access group value is nil all application access groups are being accessed. Access group name is used by all functions: set, get, delete and clear.

  */
  open var accessGroup: String? { _accessGroup }
  private let _accessGroup: String?
  
  /**
   
  Specifies whether the items can be synchronized with other devices through iCloud. Setting this property to true will
   add the item to other devices with the `set` method and obtain synchronizable items with the `get` command. Deleting synchronizable items will remove them from all devices. In order for keychain synchronization to work the user must enable "Keychain" in iCloud settings.
   
  Does not work on macOS.
   
  */
  open var synchronizable: Bool { _synchronizable }
  private let _synchronizable: Bool

  private let lock = NSLock()

  /**
  
   Instantiate a KeychainSwift object
   
  - parameter keyPrefix: a prefix that is added before the key in get/set methods. Note that `clear` method still clears everything from the Keychain.
  - parameter accessGroup: Access groups can be used to share keychain items between applications. When access group value is nil all application access groups are being accessed. Access group name is used by all functions: set, get, delete and clear.
  - parameter synchronizable: Specifies whether the items can be synchronized with other devices through iCloud. Setting this property to true will add the item to other devices with the `set` method and obtain synchronizable items with the `get` command. Deleting synchronizable items will remove them from all devices. In order for keychain synchronization to work the user must enable "Keychain" in iCloud settings. Does not work on macOS.

  */
  public init(keyPrefix: String = "", accessGroup: String? = nil, synchronizable: Bool = false) {
    self.keyPrefix = keyPrefix
    _accessGroup = accessGroup
    _synchronizable = synchronizable
  }
  
  /**
  
  Stores the text value in the keychain item under the given key.
  
  - parameter key: Key under which the text value is stored in the keychain.
  - parameter value: Text string to be written to the keychain.
  - parameter withAccess: Value that indicates when your app needs access to the text in the keychain item.
    By default the `.accessibleWhenUnlocked` option is used that permits the data to be accessed only
    while the device is unlocked by the user. Mutually exclusive with `withAccessControl`.
  - parameter withAccessControl: Access control configuration requiring user authentication
    (e.g., biometrics or passcode) to read the item. Mutually exclusive with `withAccess`.
    When provided, `kSecAttrAccessControl` is used instead of `kSecAttrAccessible`.

  */
  open func set(_ value: String, forKey key: String,
                  withAccess access: KeychainSwiftAccessOptions? = nil,
                  withAccessControl accessControl: KeychainSwiftAccessControl? = nil) throws {
    
    if let value = value.data(using: String.Encoding.utf8) {
      try set(value, forKey: key, withAccess: access, withAccessControl: accessControl)
    } else {
      throw KeychainError(errSecInvalidEncoding)
    }
  }

  /**
  
  Stores the data in the keychain item under the given key.
  
  - parameter key: Key under which the data is stored in the keychain.
  - parameter value: Data to be written to the keychain.
  - parameter withAccess: Value that indicates when your app needs access to the text in the keychain item.
    By default the `.accessibleWhenUnlocked` option is used that permits the data to be accessed only
    while the device is unlocked by the user. Mutually exclusive with `withAccessControl`.
  - parameter withAccessControl: Access control configuration requiring user authentication
    (e.g., biometrics or passcode) to read the item. Mutually exclusive with `withAccess`.
    When provided, `kSecAttrAccessControl` is used instead of `kSecAttrAccessible`.
  
  - Important: Access-controlled items cannot be synchronized via iCloud Keychain.
    Setting `synchronizable = true` with `withAccessControl` will throw an error.
  
  */
  open func set(_ value: Data, forKey key: String,
    withAccess access: KeychainSwiftAccessOptions? = nil,
    withAccessControl accessControl: KeychainSwiftAccessControl? = nil) throws {
    
    // Validate: withAccess and withAccessControl are mutually exclusive.
    // kSecAttrAccessible and kSecAttrAccessControl cannot coexist in the same query.
    if access != nil && accessControl != nil {
      throw KeychainError(errSecParam)
    }
    
    // Validate: access-controlled items are device-bound and cannot sync via iCloud Keychain.
    if accessControl != nil && synchronizable {
      throw KeychainError(errSecParam)
    }
    
    // The lock prevents the code to be run simultaneously
    // from multiple threads which may result in crashing
    lock.lock()
    defer { lock.unlock() }
    
    try deleteNoLock(key) // Delete any existing key before saving it

    let prefixedKey = keyWithPrefix(key)
      
    var query: [String : Any] = [
      KeychainSwiftConstants.klass       : kSecClassGenericPassword,
      KeychainSwiftConstants.attrAccount : prefixedKey,
      KeychainSwiftConstants.valueData   : value
    ]

    // Use access control (biometric/passcode) or simple accessibility, never both.
    // SecAccessControl embeds the accessibility level, so kSecAttrAccessible is not needed.
    if let accessControl = accessControl {
      let secAccessControl = try accessControl.createSecAccessControl()
      query[KeychainSwiftConstants.accessControl] = secAccessControl
    } else {
      let accessible = access?.value ?? KeychainSwiftAccessOptions.defaultOption.value
      query[KeychainSwiftConstants.accessible] = accessible
    }
      
    addAccessGroupWhenPresent(&query)
    addSynchronizableIfRequired(&query, addingItems: true)
    lastQueryParameters = query
    
    try throwIfFailed(SecItemAdd(query as CFDictionary, nil))
  }

  /**

  Stores the boolean value in the keychain item under the given key.

  - parameter key: Key under which the value is stored in the keychain.
  - parameter value: Boolean to be written to the keychain.
  - parameter withAccess: Value that indicates when your app needs access to the value in the keychain item.
    By default the `.accessibleWhenUnlocked` option is used that permits the data to be accessed only
    while the device is unlocked by the user. Mutually exclusive with `withAccessControl`.
  - parameter withAccessControl: Access control configuration requiring user authentication
    (e.g., biometrics or passcode) to read the item. Mutually exclusive with `withAccess`.
    When provided, `kSecAttrAccessControl` is used instead of `kSecAttrAccessible`.

  */
  open func set(_ value: Bool, forKey key: String,
    withAccess access: KeychainSwiftAccessOptions? = nil,
    withAccessControl accessControl: KeychainSwiftAccessControl? = nil) throws {
  
    let bytes: [UInt8] = value ? [1] : [0]
    let data = Data(bytes)

    try set(data, forKey: key, withAccess: access, withAccessControl: accessControl)
  }

  /**
  
  Retrieves the text value from the keychain that corresponds to the given key.
  
  - parameter key: The key that is used to read the keychain item.
  - parameter authenticationPrompt: Optional text displayed in the system biometric/passcode
    prompt when reading an access-controlled item. If nil, no prompt text is added.
  - parameter authenticationContext: Optional pre-authenticated `LAContext` (from LocalAuthentication)
    to reuse a previous authentication. Pass this to avoid repeated biometric prompts when
    reading multiple protected items. Must be an `LAContext` instance.
  - returns: The text value from the keychain. Returns nil if unable to read the item.
  
  - Important: If the item has access control, this call blocks the calling thread while the
    system authentication UI is displayed. Call from a background thread, not the main thread.
  
  */
  open func get(_ key: String,
                authenticationPrompt: String? = nil,
                authenticationContext: AnyObject? = nil) throws -> String? {
    if let data = try getData(key, authenticationPrompt: authenticationPrompt,
                              authenticationContext: authenticationContext) {
      
      if let currentString = String(data: data, encoding: .utf8) {
        return currentString
      }
      
      throw KeychainError(errSecInvalidEncoding)
    }

    return nil
  }

  /**
  
  Retrieves the data from the keychain that corresponds to the given key.
  
  - parameter key: The key that is used to read the keychain item.
  - parameter asReference: If true, returns the data as reference (needed for things like NEVPNProtocol).
  - parameter authenticationPrompt: Optional text displayed in the system biometric/passcode
    prompt when reading an access-controlled item. If nil, no prompt text is added.
  - parameter authenticationContext: Optional pre-authenticated `LAContext` (from LocalAuthentication)
    to reuse a previous authentication. Pass this to avoid repeated biometric prompts when
    reading multiple protected items. Must be an `LAContext` instance.
  - returns: The text value from the keychain. Returns nil if unable to read the item.
  
  - Important: If the item has access control, this call blocks the calling thread while the
    system authentication UI is displayed. Call from a background thread, not the main thread.
  - Throws: `KeychainError.userCanceled` if the user dismisses the authentication prompt.
    `KeychainError.authFailed` if authentication fails.
    `KeychainError.interactionNotAllowed` if the app cannot display the authentication UI
    (e.g., while in the background).
  
  */
  open func getData(_ key: String, asReference: Bool = false,
                    authenticationPrompt: String? = nil,
                    authenticationContext: AnyObject? = nil) throws -> Data? {
    // The lock prevents the code to be run simultaneously
    // from multiple threads which may result in crashing
    lock.lock()
    defer { lock.unlock() }
    
    let prefixedKey = keyWithPrefix(key)
    
    var query: [String: Any] = [
      KeychainSwiftConstants.klass       : kSecClassGenericPassword,
      KeychainSwiftConstants.attrAccount : prefixedKey,
      KeychainSwiftConstants.matchLimit  : kSecMatchLimitOne
    ]
    
    if asReference {
      query[KeychainSwiftConstants.returnReference] = kCFBooleanTrue
    } else {
      query[KeychainSwiftConstants.returnData] =  kCFBooleanTrue
    }

    // Add authentication parameters for access-controlled items.
    // These are only used when the item was stored with SecAccessControl.
    if let prompt = authenticationPrompt {
      query[KeychainSwiftConstants.useOperationPrompt] = prompt
    }

    if let context = authenticationContext {
      query[KeychainSwiftConstants.useAuthenticationContext] = context
    }
    
    addAccessGroupWhenPresent(&query)
    addSynchronizableIfRequired(&query, addingItems: false)
    lastQueryParameters = query
    
    var result: AnyObject?
    
    let lastResultCode = withUnsafeMutablePointer(to: &result) {
      SecItemCopyMatching(query as CFDictionary, UnsafeMutablePointer($0))
    }
    
    if lastResultCode != errSecItemNotFound {
      try throwIfFailed(lastResultCode)
    }
    
    return result as? Data
  }

  /**

  Retrieves the boolean value from the keychain that corresponds to the given key.

  - parameter key: The key that is used to read the keychain item.
  - parameter authenticationPrompt: Optional text displayed in the system biometric/passcode
    prompt when reading an access-controlled item. If nil, no prompt text is added.
  - parameter authenticationContext: Optional pre-authenticated `LAContext` (from LocalAuthentication)
    to reuse a previous authentication. Pass this to avoid repeated biometric prompts when
    reading multiple protected items. Must be an `LAContext` instance.
  - returns: The boolean value from the keychain. Returns nil if unable to read the item.

  */
  open func getBool(_ key: String,
                    authenticationPrompt: String? = nil,
                    authenticationContext: AnyObject? = nil) throws -> Bool? {
    guard let data = try getData(key, authenticationPrompt: authenticationPrompt,
                                 authenticationContext: authenticationContext) else { return nil }
    guard let firstBit = data.first else { return nil }
    return firstBit == 1
  }

  /**

  Deletes the single keychain item specified by the key.
  
  - parameter key: The key that is used to delete the keychain item.
  - returns: True if the item was successfully deleted.
  
  */
  @discardableResult
  open func delete(_ key: String) throws -> Bool {
    // The lock prevents the code to be run simultaneously
    // from multiple threads which may result in crashing
    lock.lock()
    defer { lock.unlock() }
    
    return try deleteNoLock(key)
  }
  
  /**
  Return all keys from keychain
   
  - returns: An string array with all keys from the keychain.
   
  */
  public var allKeys: [String] {
    lock.lock()
    defer { lock.unlock() }
      
    // Note: returnData is intentionally included. On macOS, it filters results to only
    // items this process can access. For access-controlled items with kSecMatchLimitAll,
    // items requiring interactive authentication are silently skipped rather than triggering
    // individual biometric prompts.
    var query: [String: Any] = [
      KeychainSwiftConstants.klass : kSecClassGenericPassword,
      KeychainSwiftConstants.returnData : true,
      KeychainSwiftConstants.returnAttributes: true,
      KeychainSwiftConstants.returnReference: true,
      KeychainSwiftConstants.matchLimit: KeychainSwiftConstants.secMatchLimitAll
    ]
  
    addAccessGroupWhenPresent(&query)
    addSynchronizableIfRequired(&query, addingItems: false)

    var result: AnyObject?

    let lastResultCode = withUnsafeMutablePointer(to: &result) {
      SecItemCopyMatching(query as CFDictionary, UnsafeMutablePointer($0))
    }
    
    if lastResultCode == noErr {
      return (result as? [[String: Any]])?.compactMap {
        $0[KeychainSwiftConstants.attrAccount] as? String } ?? []
    }
    
    return []
  }
    
  /**
   
  Same as `delete` but is only accessed internally, since it is not thread safe.
   
   - parameter key: The key that is used to delete the keychain item.
   - returns: True if the item was successfully deleted.
   
   */
   @discardableResult
   func deleteNoLock(_ key: String) throws -> Bool {
    let prefixedKey = keyWithPrefix(key)
    
    var query: [String: Any] = [
      KeychainSwiftConstants.klass       : kSecClassGenericPassword,
      KeychainSwiftConstants.attrAccount : prefixedKey
    ]
    
    addAccessGroupWhenPresent(&query)
    addSynchronizableIfRequired(&query, addingItems: false)
    lastQueryParameters = query
    
    let lastResultCode = SecItemDelete(query as CFDictionary)
    
    guard lastResultCode != errSecItemNotFound else { return false }
      
    try throwIfFailed(lastResultCode)
    return true
  }

  /**
  
  Deletes all Keychain items used by the app. Note that this method deletes all items regardless of the prefix settings used for initializing the class.
  
  */
  open func clear() throws {
    // The lock prevents the code to be run simultaneously
    // from multiple threads which may result in crashing
    lock.lock()
    defer { lock.unlock() }
    
    var query: [String: Any] = [ kSecClass as String : kSecClassGenericPassword ]
    addAccessGroupWhenPresent(&query)
    addSynchronizableIfRequired(&query, addingItems: false)
    lastQueryParameters = query
    
    try throwIfFailed(SecItemDelete(query as CFDictionary))
  }
  
  /// Returns the key with currently set prefix.
  func keyWithPrefix(_ key: String) -> String {
    return "\(keyPrefix)\(key)"
  }
  
  func addAccessGroupWhenPresent(_ items: inout [String: Any]) {
    guard let accessGroup = accessGroup else { return }
    
    items[KeychainSwiftConstants.accessGroup] = accessGroup
  }
  
  /**
 
  Adds kSecAttrSynchronizable: kSecAttrSynchronizableAny` item to the dictionary when the `synchronizable` property is true.
   
   - parameter items: The dictionary where the kSecAttrSynchronizable items will be added when requested.
   - parameter addingItems: Use `true` when the dictionary will be used with `SecItemAdd` method (adding a keychain item). For getting and deleting items, use `false`.
   
   - returns: the dictionary with kSecAttrSynchronizable item added if it was requested. Otherwise, it returns the original dictionary.
 
  */
  func addSynchronizableIfRequired(_ items: inout [String: Any], addingItems: Bool) {
    if !synchronizable { return }
    items[KeychainSwiftConstants.attrSynchronizable] = addingItems == true ? true : kSecAttrSynchronizableAny
  }
  
  @inlinable
  func throwIfFailed(_ status: OSStatus) throws {
    if status != noErr {
      throw KeychainError(status)
    }
  }
}

// MARK: - Async Wrappers

@available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
extension KeychainSwift {

  /**
   Asynchronously retrieves the text value from the keychain that corresponds to the given key.

   This dispatches the keychain read to a background thread, preventing the biometric/passcode
   system UI from blocking the main thread or the Swift concurrency cooperative thread pool.

   - parameter key: The key that is used to read the keychain item.
   - parameter authenticationPrompt: Optional text displayed in the system biometric/passcode prompt.
   - returns: The text value from the keychain, or nil if the item was not found.
   - throws: `KeychainError.userCanceled` if the user dismisses the authentication prompt.
  */
  public func getAsync(_ key: String,
                     authenticationPrompt: String? = nil) async throws -> String? {
    try await withCheckedThrowingContinuation { continuation in
      DispatchQueue.global(qos: .userInitiated).async {
        do {
          let value = try self.get(key, authenticationPrompt: authenticationPrompt)
          continuation.resume(returning: value)
        } catch {
          continuation.resume(throwing: error)
        }
      }
    }
  }

  /**
   Asynchronously retrieves data from the keychain that corresponds to the given key.

   This dispatches the keychain read to a background thread, preventing the biometric/passcode
   system UI from blocking the main thread or the Swift concurrency cooperative thread pool.

   - parameter key: The key that is used to read the keychain item.
   - parameter asReference: If true, returns the data as reference (needed for NEVPNProtocol).
   - parameter authenticationPrompt: Optional text displayed in the system biometric/passcode prompt.
   - returns: The data from the keychain, or nil if the item was not found.
   - throws: `KeychainError.userCanceled` if the user dismisses the authentication prompt.
  */
  public func getDataAsync(_ key: String, asReference: Bool = false,
                         authenticationPrompt: String? = nil) async throws -> Data? {
    try await withCheckedThrowingContinuation { continuation in
      DispatchQueue.global(qos: .userInitiated).async {
        do {
          let data = try self.getData(key, asReference: asReference,
                                      authenticationPrompt: authenticationPrompt)
          continuation.resume(returning: data)
        } catch {
          continuation.resume(throwing: error)
        }
      }
    }
  }

  /**
   Asynchronously retrieves a boolean value from the keychain that corresponds to the given key.

   This dispatches the keychain read to a background thread, preventing the biometric/passcode
   system UI from blocking the main thread or the Swift concurrency cooperative thread pool.

   - parameter key: The key that is used to read the keychain item.
   - parameter authenticationPrompt: Optional text displayed in the system biometric/passcode prompt.
   - returns: The boolean value from the keychain, or nil if the item was not found.
   - throws: `KeychainError.userCanceled` if the user dismisses the authentication prompt.
  */
  public func getBoolAsync(_ key: String,
                         authenticationPrompt: String? = nil) async throws -> Bool? {
    try await withCheckedThrowingContinuation { continuation in
      DispatchQueue.global(qos: .userInitiated).async {
        do {
          let value = try self.getBool(key, authenticationPrompt: authenticationPrompt)
          continuation.resume(returning: value)
        } catch {
          continuation.resume(throwing: error)
        }
      }
    }
  }
}


// ----------------------------
//
// TegKeychainConstants.swift
//
// ----------------------------

import Foundation
import Security

/// Constants used by the library
public struct KeychainSwiftConstants {
  /// Specifies a Keychain access group. Used for sharing Keychain items between apps.
  public static var accessGroup: String { return toString(kSecAttrAccessGroup) }
  
  /**
   
   A value that indicates when your app needs access to the data in a keychain item. The default value is AccessibleWhenUnlocked. For a list of possible values, see KeychainSwiftAccessOptions.
   
   */
  public static var accessible: String { return toString(kSecAttrAccessible) }
  
  /// Used for specifying a String key when setting/getting a Keychain value.
  public static var attrAccount: String { return toString(kSecAttrAccount) }

  /// Used for specifying synchronization of keychain items between devices.
  public static var attrSynchronizable: String { return toString(kSecAttrSynchronizable) }
  
  /// An item class key used to construct a Keychain search dictionary.
  public static var klass: String { return toString(kSecClass) }
  
  /// Specifies the number of values returned from the keychain. The library only supports single values.
  public static var matchLimit: String { return toString(kSecMatchLimit) }
  
  /// A return data type used to get the data from the Keychain.
  public static var returnData: String { return toString(kSecReturnData) }
  
  /// Used for specifying a value when setting a Keychain value.
  public static var valueData: String { return toString(kSecValueData) }
    
  /// Used for returning a reference to the data from the keychain
  public static var returnReference: String { return toString(kSecReturnPersistentRef) }
  
  /// A key whose value is a Boolean indicating whether or not to return item attributes
  public static var returnAttributes : String { return toString(kSecReturnAttributes) }
    
  /// A value that corresponds to matching an unlimited number of items
  public static var secMatchLimitAll : String { return toString(kSecMatchLimitAll) }

  // MARK: - Access Control

  /// Specifies a `SecAccessControl` object that governs access to the keychain item,
  /// including biometric, passcode, or user presence requirements.
  /// Mutually exclusive with `accessible` (`kSecAttrAccessible`).
  public static var accessControl: String { return toString(kSecAttrAccessControl) }

  /// A string displayed in the system authentication prompt (Face ID / Touch ID / passcode)
  /// when reading an access-controlled keychain item. Pass this in the query dictionary
  /// to customize the reason shown to the user.
  public static var useOperationPrompt: String { return toString(kSecUseOperationPrompt) }

  /// An `LAContext` object used to authenticate access to keychain items.
  /// Passing a pre-authenticated `LAContext` allows reusing a single authentication
  /// for multiple keychain reads within the context's validity window, avoiding
  /// repeated biometric prompts.
  public static var useAuthenticationContext: String { return toString(kSecUseAuthenticationContext) }

  static func toString(_ value: CFString) -> String {
    return value as String
  }
}


// ----------------------------
//
// KeychainSwiftAccessOptions.swift
//
// ----------------------------

import Security

/**

These options are used to determine when a keychain item should be readable. The default value is AccessibleWhenUnlocked.

*/
public enum KeychainSwiftAccessOptions: Sendable {
  
  /**
  
  The data in the keychain item can be accessed only while the device is unlocked by the user.
  
  This is recommended for items that need to be accessible only while the application is in the foreground. Items with this attribute migrate to a new device when using encrypted backups.
  
  This is the default value for keychain items added without explicitly setting an accessibility constant.
  
  */
  case accessibleWhenUnlocked
  
  /**
  
  The data in the keychain item can be accessed only while the device is unlocked by the user.
  
  This is recommended for items that need to be accessible only while the application is in the foreground. Items with this attribute do not migrate to a new device. Thus, after restoring from a backup of a different device, these items will not be present.
  
  */
  case accessibleWhenUnlockedThisDeviceOnly
  
  /**
  
  The data in the keychain item cannot be accessed after a restart until the device has been unlocked once by the user.
  
  After the first unlock, the data remains accessible until the next restart. This is recommended for items that need to be accessed by background applications. Items with this attribute migrate to a new device when using encrypted backups.
  
  */
  case accessibleAfterFirstUnlock
  
  /**
  
  The data in the keychain item cannot be accessed after a restart until the device has been unlocked once by the user.
  
  After the first unlock, the data remains accessible until the next restart. This is recommended for items that need to be accessed by background applications. Items with this attribute do not migrate to a new device. Thus, after restoring from a backup of a different device, these items will not be present.
  
  */
  case accessibleAfterFirstUnlockThisDeviceOnly

  /**
  
  The data in the keychain can only be accessed when the device is unlocked. Only available if a passcode is set on the device.
  
  This is recommended for items that only need to be accessible while the application is in the foreground. Items with this attribute never migrate to a new device. After a backup is restored to a new device, these items are missing. No items can be stored in this class on devices without a passcode. Disabling the device passcode causes all items in this class to be deleted.
  
  */
  case accessibleWhenPasscodeSetThisDeviceOnly
  
  static var defaultOption: KeychainSwiftAccessOptions {
    return .accessibleWhenUnlocked
  }

  /// Returns the corresponding `CFString` constant for use with `SecAccessControlCreateWithFlags`.
  /// Unlike `value` (which returns a `String`), this returns the original `CFString` type
  /// needed as the `protection` parameter.
  var cfValue: CFString {
    switch self {
    case .accessibleWhenUnlocked:
      return kSecAttrAccessibleWhenUnlocked

    case .accessibleWhenUnlockedThisDeviceOnly:
      return kSecAttrAccessibleWhenUnlockedThisDeviceOnly

    case .accessibleAfterFirstUnlock:
      return kSecAttrAccessibleAfterFirstUnlock

    case .accessibleAfterFirstUnlockThisDeviceOnly:
      return kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly

    case .accessibleWhenPasscodeSetThisDeviceOnly:
      return kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly
    }
  }

  var value: String {
    switch self {
    case .accessibleWhenUnlocked:
      return toString(kSecAttrAccessibleWhenUnlocked)
      
    case .accessibleWhenUnlockedThisDeviceOnly:
      return toString(kSecAttrAccessibleWhenUnlockedThisDeviceOnly)
      
    case .accessibleAfterFirstUnlock:
      return toString(kSecAttrAccessibleAfterFirstUnlock)
      
    case .accessibleAfterFirstUnlockThisDeviceOnly:
      return toString(kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly)
      
    case .accessibleWhenPasscodeSetThisDeviceOnly:
      return toString(kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly)
    }
  }
  
  func toString(_ value: CFString) -> String {
    return KeychainSwiftConstants.toString(value)
  }
}


// ----------------------------
//
// KeychainSwiftAccessControl.swift
//
// ----------------------------

import Security
import Foundation

/**

 Represents an access control configuration for keychain items that combines
 an accessibility level with access control flags (e.g., biometric or passcode requirements).

 Use this type with the `withAccessControl` parameter on `set` methods to require
 user authentication (Face ID, Touch ID, or device passcode) when accessing keychain items.

 - Important: `kSecAttrAccessControl` and `kSecAttrAccessible` are mutually exclusive.
   When you provide a `KeychainSwiftAccessControl`, the library uses `kSecAttrAccessControl`
   and does NOT set `kSecAttrAccessible` separately. The accessibility level is embedded
   in the access control object.

 - Important: Access-controlled items cannot be synchronized via iCloud Keychain.
   Attempting to use `synchronizable = true` with access control will throw an error.

 - Important: Reading an access-controlled item triggers a system authentication prompt
   (Face ID, Touch ID, or passcode). This blocks the calling thread until the user
   responds. Always call `get`/`getData`/`getBool` from a background thread, never from
   the main thread.

 ## Presets

 ```swift
 // Biometric only — invalidated when biometric enrollment changes
 let accessControl = KeychainSwiftAccessControl.biometricCurrentSet()

 // Biometric with any enrollment — survives biometric changes
 let accessControl = KeychainSwiftAccessControl.biometricAny()

 // Biometric preferred, device passcode as fallback
 let accessControl = KeychainSwiftAccessControl.biometricOrPasscode()

 // Device passcode only
 let accessControl = KeychainSwiftAccessControl.devicePasscode()

 // System decides (biometric or passcode)
 let accessControl = KeychainSwiftAccessControl.userPresence()
 ```

 ## Custom Configuration

 ```swift
 // Custom flags with custom accessibility
 let accessControl = KeychainSwiftAccessControl(
     accessibility: .accessibleWhenPasscodeSetThisDeviceOnly,
     flags: [.biometryCurrentSet, .or, .devicePasscode]
 )
 ```

*/
public struct KeychainSwiftAccessControl: Sendable {

  // MARK: - Properties

  /// The base accessibility level for the keychain item.
  /// This determines *when* the item can be accessed relative to the device lock state,
  /// and is passed as the first parameter to `SecAccessControlCreateWithFlags`.
  public let accessibility: KeychainSwiftAccessOptions

  /// The access control flags specifying *how* the user must authenticate.
  /// These map directly to `SecAccessControlCreateFlags` values such as
  /// `.biometryCurrentSet`, `.biometryAny`, `.devicePasscode`, and `.userPresence`.
  public let flags: SecAccessControlCreateFlags

  // MARK: - Initialization

  /**
   Creates an access control configuration with the given accessibility and flags.

   - parameter accessibility: The base accessibility level. Defaults to
     `.accessibleWhenPasscodeSetThisDeviceOnly`, which is the most secure option
     and is recommended for biometric-protected items. This ensures items are
     deleted if the device passcode is removed.
   - parameter flags: The `SecAccessControlCreateFlags` to apply. Common values include
     `.biometryCurrentSet`, `.biometryAny`, `.devicePasscode`, and `.userPresence`.
  */
  public init(
    accessibility: KeychainSwiftAccessOptions = .accessibleWhenPasscodeSetThisDeviceOnly,
    flags: SecAccessControlCreateFlags
  ) {
    self.accessibility = accessibility
    self.flags = flags
  }

  // MARK: - Presets

  /**
   Biometric only — tied to the *current* biometric enrollment.

   If the user adds or removes a fingerprint or Face ID profile after the item is stored,
   the keychain item becomes permanently inaccessible (effectively destroyed). This provides
   the strongest guarantee that a biometric change by a malicious actor cannot unlock
   existing secrets. There is no passcode fallback.

   - parameter accessibility: The base accessibility level.
     Defaults to `.accessibleWhenPasscodeSetThisDeviceOnly`.
   - returns: A configured `KeychainSwiftAccessControl`.
  */
  @available(macOS 10.13.4, iOS 11.3, watchOS 4.3, tvOS 11.3, *)
  public static func biometricCurrentSet(
    accessibility: KeychainSwiftAccessOptions = .accessibleWhenPasscodeSetThisDeviceOnly
  ) -> KeychainSwiftAccessControl {
    KeychainSwiftAccessControl(accessibility: accessibility, flags: .biometryCurrentSet)
  }

  /**
   Biometric with any enrolled biometric — survives biometric enrollment changes.

   Access is granted with any currently enrolled biometric (Face ID or Touch ID).
   The item remains accessible even if the user adds or removes biometric profiles
   after storage. There is no passcode fallback.

   - parameter accessibility: The base accessibility level.
     Defaults to `.accessibleWhenPasscodeSetThisDeviceOnly`.
   - returns: A configured `KeychainSwiftAccessControl`.
  */
  @available(macOS 10.13.4, iOS 11.3, watchOS 4.3, tvOS 11.3, *)
  public static func biometricAny(
    accessibility: KeychainSwiftAccessOptions = .accessibleWhenPasscodeSetThisDeviceOnly
  ) -> KeychainSwiftAccessControl {
    KeychainSwiftAccessControl(accessibility: accessibility, flags: .biometryAny)
  }

  /**
   Biometric preferred, with device passcode as fallback.

   The system tries biometrics first (Face ID or Touch ID). If biometrics are unavailable
   or the user taps "Enter Password", the device passcode is accepted instead.
   This is the most user-friendly option for access-controlled items.

   - parameter accessibility: The base accessibility level.
     Defaults to `.accessibleWhenPasscodeSetThisDeviceOnly`.
   - returns: A configured `KeychainSwiftAccessControl`.
  */
  @available(macOS 10.13.4, iOS 11.3, watchOS 4.3, tvOS 11.3, *)
  public static func biometricOrPasscode(
    accessibility: KeychainSwiftAccessOptions = .accessibleWhenPasscodeSetThisDeviceOnly
  ) -> KeychainSwiftAccessControl {
    KeychainSwiftAccessControl(
      accessibility: accessibility,
      flags: [.biometryAny, .or, .devicePasscode]
    )
  }

  /**
   Device passcode only — no biometric authentication.

   The user must enter their device passcode to access the item.
   Biometrics are not offered.

   - parameter accessibility: The base accessibility level.
     Defaults to `.accessibleWhenPasscodeSetThisDeviceOnly`.
   - returns: A configured `KeychainSwiftAccessControl`.
  */
  public static func devicePasscode(
    accessibility: KeychainSwiftAccessOptions = .accessibleWhenPasscodeSetThisDeviceOnly
  ) -> KeychainSwiftAccessControl {
    KeychainSwiftAccessControl(accessibility: accessibility, flags: .devicePasscode)
  }

  /**
   User presence — lets the system decide the best authentication method.

   The system chooses biometrics or passcode depending on what's available and
   the current context. This is the most flexible option.

   - parameter accessibility: The base accessibility level.
     Defaults to `.accessibleWhenPasscodeSetThisDeviceOnly`.
   - returns: A configured `KeychainSwiftAccessControl`.
  */
  public static func userPresence(
    accessibility: KeychainSwiftAccessOptions = .accessibleWhenPasscodeSetThisDeviceOnly
  ) -> KeychainSwiftAccessControl {
    KeychainSwiftAccessControl(accessibility: accessibility, flags: .userPresence)
  }

  // MARK: - Internal

  /**
   Creates the `SecAccessControl` object from this configuration.

   This calls `SecAccessControlCreateWithFlags` with the configured accessibility
   and flags. The resulting object is used as the value for `kSecAttrAccessControl`
   in keychain queries.

   - throws: `KeychainError` if the access control object could not be created
     (e.g., invalid flag combinations or unsupported accessibility level).
   - returns: A `SecAccessControl` instance ready for use in keychain operations.
  */
  func createSecAccessControl() throws -> SecAccessControl {
    var error: Unmanaged<CFError>?

    guard let access = SecAccessControlCreateWithFlags(
      kCFAllocatorDefault,
      accessibility.cfValue,
      flags,
      &error
    ) else {
      // Extract the OSStatus from the CFError if available, otherwise use a generic param error
      if let cfError = error?.takeRetainedValue() {
        let nsError = cfError as Error as NSError
        throw KeychainError(OSStatus(nsError.code))
      }
      throw KeychainError(errSecParam)
    }

    return access
  }
}


